# Generated by Django 3.1.7 on 2021-03-13 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_delete_test'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='unionboard',
            table='new',
        ),
    ]
