# Generated by Django 3.1.7 on 2021-03-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_auto_20210313_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionBoard',
            fields=[
                ('url', models.CharField(max_length=190, primary_key=True, serialize=False)),
                ('shop_url', models.CharField(blank=True, max_length=190, null=True)),
                ('pro_name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_fee', models.CharField(blank=True, max_length=100, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('img_path', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auction_board',
                'managed': False,
            },
        ),
    ]
