# Generated by Django 3.1.7 on 2021-03-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_auctionboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoolBoard',
            fields=[
                ('url', models.CharField(max_length=190, primary_key=True, serialize=False)),
                ('shop_url', models.CharField(blank=True, max_length=190, null=True)),
                ('pro_name', models.CharField(blank=True, max_length=190, null=True)),
                ('price', models.CharField(blank=True, max_length=190, null=True)),
                ('delivery_fee', models.CharField(blank=True, max_length=190, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('img_path', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cool_board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoupangBoard',
            fields=[
                ('url', models.CharField(max_length=190, primary_key=True, serialize=False)),
                ('shop_url', models.CharField(blank=True, max_length=190, null=True)),
                ('pro_name', models.CharField(blank=True, max_length=190, null=True)),
                ('price', models.CharField(blank=True, max_length=190, null=True)),
                ('delivery_fee', models.CharField(blank=True, max_length=190, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('img_path', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'coupang_board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ElevenBoard',
            fields=[
                ('url', models.CharField(max_length=190, primary_key=True, serialize=False)),
                ('shop_url', models.CharField(blank=True, max_length=190, null=True)),
                ('pro_name', models.CharField(blank=True, max_length=190, null=True)),
                ('price', models.CharField(blank=True, max_length=190, null=True)),
                ('delivery_fee', models.CharField(blank=True, max_length=190, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('img_path', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'eleven_board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FmBoard',
            fields=[
                ('url', models.CharField(max_length=190, primary_key=True, serialize=False)),
                ('shop_url', models.CharField(blank=True, max_length=190, null=True)),
                ('pro_name', models.CharField(blank=True, max_length=190, null=True)),
                ('price', models.CharField(blank=True, max_length=190, null=True)),
                ('delivery_fee', models.CharField(blank=True, max_length=190, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('img_path', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'fm_board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GmarketBoard',
            fields=[
                ('url', models.CharField(max_length=190, primary_key=True, serialize=False)),
                ('shop_url', models.CharField(blank=True, max_length=190, null=True)),
                ('pro_name', models.CharField(blank=True, max_length=190, null=True)),
                ('price', models.CharField(blank=True, max_length=190, null=True)),
                ('delivery_fee', models.CharField(blank=True, max_length=190, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('img_path', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'gmarket_board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OverseeBoard',
            fields=[
                ('url', models.CharField(max_length=190, primary_key=True, serialize=False)),
                ('shop_url', models.CharField(blank=True, max_length=190, null=True)),
                ('pro_name', models.CharField(blank=True, max_length=190, null=True)),
                ('price', models.CharField(blank=True, max_length=190, null=True)),
                ('delivery_fee', models.CharField(blank=True, max_length=190, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('img_path', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'oversee_board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PpBoard',
            fields=[
                ('url', models.CharField(max_length=190, primary_key=True, serialize=False)),
                ('shop_url', models.CharField(blank=True, max_length=190, null=True)),
                ('pro_name', models.CharField(blank=True, max_length=190, null=True)),
                ('price', models.CharField(blank=True, max_length=190, null=True)),
                ('delivery_fee', models.CharField(blank=True, max_length=190, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('img_path', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'pp_board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RuliBoard',
            fields=[
                ('url', models.CharField(max_length=190, primary_key=True, serialize=False)),
                ('shop_url', models.CharField(blank=True, max_length=190, null=True)),
                ('pro_name', models.CharField(blank=True, max_length=190, null=True)),
                ('price', models.CharField(blank=True, max_length=190, null=True)),
                ('delivery_fee', models.CharField(blank=True, max_length=190, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('img_path', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ruli_board',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='unionboard',
            table='union_board',
        ),
    ]
